// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.ProcTime;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Empty)
    com.google.protobuf.MessageOrBuilder {
}
