// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.ProcTime;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *where string would be in my message
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <pre>
   *where string would be in my message
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
