// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.ProcTime;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responsemessage = 1;</code>
   */
  java.lang.String getResponsemessage();
  /**
   * <code>string responsemessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponsemessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
