// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.ProcTime;

public interface ScheduleMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ScheduleMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string text = 2;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
