// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.ProcTime;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ScheduleMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ScheduleMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\005proto\"2\n\014LoginRequest\022" +
      "\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"@\n\017R" +
      "esponseMessage\022\027\n\017responsemessage\030\001 \001(\t\022" +
      "\024\n\014responseCode\030\002 \001(\005\"-\n\017ScheduleMessage" +
      "\022\014\n\004date\030\001 \001(\t\022\014\n\004text\030\002 \001(\t\"\007\n\005Empty2\300\001" +
      "\n\014LoginAccount\0229\n\nEnterlogin\022\023.proto.Log" +
      "inRequest\032\026.proto.ResponseMessage\022E\n\023Use" +
      "raccountschedule\022\026.proto.ScheduleMessage" +
      "\032\026.proto.ResponseMessage\022.\n\006logout\022\014.pro" +
      "to.Empty\032\026.proto.ResponseMessageB\037\n\rgrpc" +
      ".ProcTimeB\014Service1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_proto_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ResponseMessage_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_proto_ScheduleMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ScheduleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ScheduleMessage_descriptor,
        new java.lang.String[] { "Date", "Text", });
    internal_static_proto_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
